### ISSUE TITLE
Incorrect queue size for spdlog

### ISSUE THREAD

**Issue by gabime** [sandboxgod/LogProfiler#1]
spdlog’s default async queue is only 8192, and blocks if exceeds it.
Your bench logs total of 1 million entries to same queue  ((1+2+3+4)threads x 100000 iterations).
To get a fair comparison set the queue size to 1,000,000.
Also, you might want to add synchronous logging bench, which sometimes is faster in spdlog.

**Comment by sandboxcoder** [comment]
Thanks for taking the time to leave feedback. I just uploaded a correction which can be viewed here:
https://github.com/sandboxgod/LogProfiler/commit/8a310d1d21c61c33ac1b20773abb6db5aec96178

However, at least on my Macbook Pro here it seems to be a little slower than Qt Logging and g3log. Do you have any ideas what I could be missing? I'm actually very perplexed because on my Windows 10 64-Bit PC spdlog was by far the fastest at least during the "1 Thread" case

Leaving this issue open for now.

**Comment by gabime** [comment]
I think that mutex under osx is much slower (lack of futex?) see 
https://stackoverflow.com/questions/22899053/why-is-stdmutex-so-slow-on-osx

Also counting in micros is not accurate enough. spdlog’s (at least under linux and windows) latency is much less than 1 micro

**Comment by sandboxcoder** [comment]
Thanks for the feedback I'll make the correction later tonight (basically, just the high resolution clock like spdlog does in it's benchmarks) and make sure to use results from either Linux or Windows
